---
root: true
parserOptions:
  ecmaVersion: 2022
  sourceType: script
env:
  node: true
  es6: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:editorconfig/all"
plugins:
  - "editorconfig"
