---
name: Bug Report
description: File a bug report
labels: ["type: bug"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also share, what did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: runtime-information
    attributes:
      label: Please provide runtime information.
      description: Runtime information, e.g. artifact version and other environment relevant information.
    validations:
      required: true

  - type: textarea
    id: log-output
    attributes:
      label: Relevant log output
      description: Please provide any relevant log output. Check for private info before submitting.
      render: shell

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How can this issue be reproduced?
      description: Instructions on how this issue can be reproduced.
